### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by jiangSeu** [luwanglin/GaitSet_learning#1]
你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
具体是卡在 nn.DataParallel()，将这句代码注释后
又卡在.cuda()
不知道怎么解决. 求解答

版本：pytorch0.4 cuda9.0

**Comment by luwanglin** [comment]
> 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> 具体是卡在 nn.DataParallel()，将这句代码注释后
> 又卡在.cuda()
> 不知道怎么解决. 求解答
> 
> 版本：pytorch0.4 cuda9.0

稍后我再commit一下代码，我使用的是pytorch1.3，cuda10.2

**Comment by jiangSeu** [comment]
> > 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> > 具体是卡在 nn.DataParallel()，将这句代码注释后
> > 又卡在.cuda()
> > 不知道怎么解决. 求解答
> > 版本：pytorch0.4 cuda9.0
> 
> 稍后我再commit一下代码，我使用的是pytorch1.3，cuda10.2

**Comment by jiangSeu** [comment]
> > 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> > 具体是卡在 nn.DataParallel()，将这句代码注释后
> > 又卡在.cuda()
> > 不知道怎么解决. 求解答
> > 版本：pytorch0.4 cuda9.0
> 
> 稍后我再commit一下代码，我使用的是pytorch1.3，cuda1

请问您是在window下还是centOs下呢？ 相比原来的代码，有改哪些东西嘛

**Comment by jiangSeu** [comment]
训练时报错情况：

![image](https://user-images.githubusercontent.com/71956241/96806929-e6106600-1447-11eb-9199-2a5e771c18fd.png)

**Comment by luwanglin** [comment]
> > > 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> > > 具体是卡在 nn.DataParallel()，将这句代码注释后
> > > 又卡在.cuda()
> > > 不知道怎么解决. 求解答
> > > 版本：pytorch0.4 cuda9.0
> > 
> > 
> > 稍后我再commit一下代码，我使用的是pytorch1.3，cuda1
> 
> 请问您是在window下还是centOs下呢？ 相比原来的代码，有改哪些东西嘛

我的是在Ubuntu18下的运行的，现在最新的代码我的是能正常运行的

**Comment by jiangSeu** [comment]
> > > > 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> > > > 具体是卡在 nn.DataParallel()，将这句代码注释后
> > > > 又卡在.cuda()
> > > > 不知道怎么解决. 求解答
> > > > 版本：pytorch0.4 cuda9.0
> > > 
> > > 
> > > 稍后我再commit一下代码，我使用的是pytorch1.3，cuda1
> > 
> > 
> > 请问您是在window下还是centOs下呢？ 相比原来的代码，有改哪些东西嘛
> 
> 我的是在Ubuntu18下的运行的，现在最新的代码我的是能正常运行的

您好 请问可否发一下pretreatment处理之后的数据给我，1187714583@qq.com。我排查一下错误，非常感谢！

**Comment by luwanglin** [comment]
> > > > > 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> > > > > 具体是卡在 nn.DataParallel()，将这句代码注释后
> > > > > 又卡在.cuda()
> > > > > 不知道怎么解决. 求解答
> > > > > 版本：pytorch0.4 cuda9.0
> > > > 
> > > > 
> > > > 稍后我再commit一下代码，我使用的是pytorch1.3，cuda1
> > > 
> > > 
> > > 请问您是在window下还是centOs下呢？ 相比原来的代码，有改哪些东西嘛
> > 
> > 
> > 我的是在Ubuntu18下的运行的，现在最新的代码我的是能正常运行的
> 
> 您好 请问可否发一下pretreatment处理之后的数据给我，[1187714583@qq.com](mailto:1187714583@qq.com)。我排查一下错误，非常感谢！

您好，请问你有下载CASIA-B和OUMVLP数据集吗

**Comment by jiangSeu** [comment]
> > > > > > 你好 请问你的代码可以运行成功吗 我这边一直卡在 Initializing modle...
> > > > > > 具体是卡在 nn.DataParallel()，将这句代码注释后
> > > > > > 又卡在.cuda()
> > > > > > 不知道怎么解决. 求解答
> > > > > > 版本：pytorch0.4 cuda9.0
> > > > > 
> > > > > 
> > > > > 稍后我再commit一下代码，我使用的是pytorch1.3，cuda1
> > > > 
> > > > 
> > > > 请问您是在window下还是centOs下呢？ 相比原来的代码，有改哪些东西嘛
> > > 
> > > 
> > > 我的是在Ubuntu18下的运行的，现在最新的代码我的是能正常运行的
> > 
> > 
> > 您好 请问可否发一下pretreatment处理之后的数据给我，[1187714583@qq.com](mailto:1187714583@qq.com)。我排查一下错误，非常感谢！
> 
> 您好，请问你有下载CASIA-B和OUMVLP数据集吗

下载了，但是报错似乎显示 我用pretreatment.py 处理之后的输出数据有问题
